### ISSUE TITLE
Intermittend IOException "Cannot append to finished buffer" in mc-mms-client-0.3.jar

### ISSUE THREAD

**Issue by NikMel** [MaritimeCloud/MaritimeCloud#31]
Sorry if posting in the wrong place...

We've been getting this IOException on both the client and server side for a while. On the server side (log posted below) it's consistent, we see it on Wildfly (8.2.0) every time we deploy a new build. 
On the client side (POJO) it seems to be intermittent, once in a while we get a couple of warnings, but then it seems to work (and we get the proper reply from the server).

This is the exception from Wildfly (the server):
```
20:17:11,339 WARN  [net.maritimecloud.internal.mms.client.connection.transport.ClientTransportJsr356] (WebSocketClient@923139407-325) Unhandled Error (closing connection): java.io.IOException: Cannot append to finished buffer
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.appendFrame(SimpleTextMessage.java:47) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:60) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:359) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [mc-mms-client-0.3.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60]

20:17:11,393 WARN  [org.eclipse.jetty.websocket.common.Parser] (WebSocketClient@923139407-325) : org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:280) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [mc-mms-client-0.3.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60]
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:259) [mc-mms-client-0.3.jar:]
	... 6 more

20:17:11,394 WARN  [org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection] (WebSocketClient@923139407-325) : org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:280) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [mc-mms-client-0.3.jar:]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [mc-mms-client-0.3.jar:]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_60]
Caused by: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:259) [mc-mms-client-0.3.jar:]
	... 6 more
```
Let me know i I can provide with any more details.

All the best 
Niklas

**Comment by NikMel** [comment]
Just got the exception on the client side. Attaching the log output
```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
2015-08-30 20:34:38.793:INFO::main: Logging initialized @1148ms
Aug 30, 2015 8:34:39 PM net.maritimecloud.internal.util.logging.JDKLogger log
INFO: Trying to connect to ws://localhost:43234/
2015-08-30 20:34:40.228:WARN:nmimcct.ClientTransportJsr356:WebSocketClient@842120670-24: Unhandled Error (closing connection)
java.io.IOException: Cannot append to finished buffer
	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.appendFrame(SimpleTextMessage.java:47)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:60)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrAnnotatedEventDriver.onTextFrame(JsrAnnotatedEventDriver.java:359)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Aug 30, 2015 8:34:40 PM net.maritimecloud.internal.util.logging.JDKLogger log
INFO: Socket closed
2015-08-30 20:34:40.237:WARN:oejwc.Parser:WebSocketClient@842120670-24: 
org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:280)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:259)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
2015-08-30 20:34:40.238:WARN:oejwci.AbstractWebSocketConnection:WebSocketClient@842120670-24: 
org.eclipse.jetty.websocket.api.WebSocketException: java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:280)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 
java.lang.NullPointerException
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:259)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Aug 30, 2015 8:34:40 PM net.maritimecloud.internal.util.logging.JDKLogger log
INFO: Trying to connect to ws://localhost:43234/
Aug 30, 2015 8:34:40 PM net.maritimecloud.internal.util.logging.JDKLogger log
INFO: Connected to  ws://localhost:43234/
```

**Comment by kaspernielsen** [comment]
Yeah we have been having the issue for some time.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=469225

I've never been able to consistently reproduce it unfortunately

**Comment by kaspernielsen** [comment]
Any chance that you can send me the build you deploy? Or any other thing that can help me reproduce it

**Comment by NikMel** [comment]
Hi Kasper,

Here's a link to the deployment: http://brink.viktoria.chalmers.se/bamboo/browse/POR-DEM-167/artifact/shared/Application/PortCDM.ear

Put the attached configuration file in one of the following folders:
/etc/portcdm
~/.portcdm

Start maritime cloud on your local machine (or change the url for the setting global.maritimecloud.host in the attached configuration file).

Deploy and undeploy it a few times (I just tried 4 times and got the issue once). It may happen more often if maritime cloud and wildfly are deployed on the same server (its just a feeling I got, so...).

Let me know if you need more assistance with deploying...

All the best
/Niklas



On 2015-08-31 10:16, Kasper Nielsen wrote:

Any chance that you can send me the build you deploy? Or any other thing that can help me reproduce it

—
Reply to this email directly or view it on GitHub<https://github.com/MaritimeCloud/MaritimeCloud/issues/31#issuecomment-136297388>.

--
Niklas Mellegård, PhD
Senior Researcher

[cid:part3.09060504.09010702@viktoria.se]

Viktoria Swedish ICT AB
Lindholmspiren 3A
SE-417 56 Göteborg, Sweden
Tel: +46 73 996 5339
E-mail: niklas.mellegard@viktoria.se<mailto:niklas.mellegard@viktoria.se>
www.viktoria.se<http://www.viktoria.se>

Part of RISE

# Global
global.maritimecloud.host = localhost:43234
global.maritimecloud.latitude = 57.7036265
global.maritimecloud.longitude = 11.9291319
global.maritimecloud.organization = Your organization

# Port Info
port-info.port.code = SEGOT
port-info.port.name = Port of Gothenburg
port-info.port.latitude = 57.7036265
port-info.port.longitude = 11.9291319
port-info.homepage = http://www.portofgothenburg.com/
port-info.logo = http://www.portofgothenburg.com/Handlers/TransformedImage.ashx?url=%2fGlobal%2fPortGbg_payoff_BLUE+beskuren.jpg&w=150&rm=fit
port-info.port.country = Sweden
port-info.port.country_code = SE
port-info.port.city = Gothenburg

# Port Call Manager
portcallmanager.maritimecloud.name = Port Call Manager
portcallmanager.maritimecloud.endpointid = mmsi:813000000
portcallmanager.maritimecloud.description = Your description

# Port Call Status, broadcast
portcallstatus-broadcast.maritimecloud.name = Port Call Status
portcallstatus-broadcast.maritimecloud.endpointid = mmsi:812100000
portcallstatus-broadcast.maritimecloud.description = Your description

# Port Call Status, service
portcallstatus-service.maritimecloud.name = Port Call Status
portcallstatus-service.maritimecloud.endpointid = mmsi:812000000
portcallstatus-service.maritimecloud.description = Your description

# Process Manager
processmanager.maritimecloud.name = Process Manager
processmanager.maritimecloud.endpointid = mmsi:81400000
processmanager.maritimecloud.description = Your description

# Data Dictionary
#state-catalogue.maritimecloud.endpointid = mmsi:815000000
data-dictionary.maritimecloud.name = Data Dictionary
data-dictionary.maritimecloud.description = Your description
data-dictionary.state-type-catalogue.endpointid = mmsi:815000000
data-dictionary.info-type-catalogue.endpointid = mmsi:815000005

# Update State
updatestate.maritimecloud.name = Update State
updatestate.maritimecloud.endpointid = mmsi:811000000
#updatestate.maritimecloud.clientid = mmsi:444444441
updatestate.maritimecloud.description = Your description

# Port Statistics
port-statistics.maritimecloud.name = Port Statistics Service
port-statistics.maritimecloud.endpointid = mmsi:817000000
#port-statistics.maritimecloud.clientid = mmsi:333333331
port-statistics.maritimecloud.description = Your description

**Comment by kaspernielsen** [comment]
> On the server side (log posted below) it's consistent, we see it on Wildfly (8.2.0) every time we deploy a new build. 

Just a follow up question. Is it the server side you are deploying on a Wildfly or is it the client?

**Comment by NikMel** [comment]
This is the server side.

Den 31 aug 2015 12:30 em skrev Kasper Nielsen <notifications@github.com>:

On the server side (log posted below) it's consistent, we see it on Wildfly (8.2.0) every time we deploy a new build.

Just a follow up question. Is it the server side you are deploying on a Wildfly or is it the client?

**Comment by kaspernielsen** [comment]
Any reason you are not starting up the MMS server as a standalone process?

**Comment by kaspernielsen** [comment]
Also what should I name the configuration file?

**Comment by NikMel** [comment]
The name should be: portcdm_server.conf (I replied via email, it seems github messed up the formatting a bit...).

And in case the reply about MMS server didn't reach you: 
I was unclear. The MMS server is started as a standalone process ('java -jar mc-mms[etc]'), and is not run in wildfly (we will start routing through your MMS-server next week).

/N

**Comment by kaspernielsen** [comment]
okay so only mms-client side you the exceptions?
Or also mms-server side?

**Comment by kaspernielsen** [comment]
I get this issue when I try to deploy the ear


15:55:00,330 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 2) JBAS014613: Operation ("deploy") failed - address: ({"deployment" => "PortCDM.ear"}) - failure description: {"JBAS014771: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"PortCDM.ear#se.viktoria.monalisa.portcdm.core.domain\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.PortCDMXADS]",
    "jboss.persistenceunit.\"PortCDM.ear/service-1.0-SNAPSHOT.war#se.viktoria.monalisa.portcdm.core.domain\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.PortCDMXADS]"
]}
15:55:00,331 ERROR [org.jboss.as.server] (management-handler-thread - 2) JBAS015870: Deploy of deployment "PortCDM.ear" was rolled back with the following failure message:
{"JBAS014771: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"PortCDM.ear#se.viktoria.monalisa.portcdm.core.domain\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.PortCDMXADS]",
    "jboss.persistenceunit.\"PortCDM.ear/service-1.0-SNAPSHOT.war#se.viktoria.monalisa.portcdm.core.domain\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.PortCDMXADS]"
]}

**Comment by NikMel** [comment]
We get the exceptions on both client and server side. But, I think (just a feeling) it happens more consistently on the server side when deploying an ear. When I deploy on my local wildfly (and having MMS Server running locally), it happens regularly (perhaps once every 4-5 times I deploy).

**Comment by kaspernielsen** [comment]
I've attempted to reopen the Jetty issue. Lets see what happens. It should effect operations. But I know the error messages are annoying
